// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha1

import (
	jsonpb "github.com/golang/protobuf/jsonpb"
)

var (
	CommonMarshaler   = &jsonpb.Marshaler{}
	CommonUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
