// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for RateLimiting
func (this *RateLimiting) MarshalJSON() ([]byte, error) {
	str, err := RateLimitingMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RateLimiting
func (this *RateLimiting) UnmarshalJSON(b []byte) error {
	return RateLimitingUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RateLimiting_Config
func (this *RateLimiting_Config) MarshalJSON() ([]byte, error) {
	str, err := RateLimitingMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RateLimiting_Config
func (this *RateLimiting_Config) UnmarshalJSON(b []byte) error {
	return RateLimitingUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	RateLimitingMarshaler   = &jsonpb.Marshaler{}
	RateLimitingUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
