// Code generated by protoc-gen-go. DO NOT EDIT.
// source: policy/resilience/v1alpha1/circuit_breaker.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	math "math"
	v1alpha1 "opensergo.io/api/core/v1alpha1"
	v1alpha11 "opensergo.io/api/policy/v1alpha1"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// <!-- crd generation tags
// +cue-gen:CircuitBreaker:groupName:resilience.policy.opensergo.io
// +cue-gen:CircuitBreaker:version:v1alpha1
// +cue-gen:CircuitBreaker:annotations:helm.sh/resource-policy=keep
// +cue-gen:CircuitBreaker:subresource:status
// +cue-gen:CircuitBreaker:scope:Namespaced
// +cue-gen:CircuitBreaker:resource:categories=opensergo-io
// +cue-gen:CircuitBreaker:preserveUnknownFields:false
// -->
//
// <!-- go code generation tags
// +kubetype-gen
// +kubetype-gen:groupVersion=resilience.policy.opensergo.io/v1alpha1
// +genclient
// +k8s:deepcopy-gen=true
// -->
type CircuitBreaker struct {
	Selector *v1alpha1.Selector     `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	Config   *CircuitBreaker_Config `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	// The fallback action when the circuit breaker works.
	Action               *v1alpha11.FallbackAction `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *CircuitBreaker) Reset()         { *m = CircuitBreaker{} }
func (m *CircuitBreaker) String() string { return proto.CompactTextString(m) }
func (*CircuitBreaker) ProtoMessage()    {}
func (*CircuitBreaker) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e7ca0736978053, []int{0}
}

func (m *CircuitBreaker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CircuitBreaker.Unmarshal(m, b)
}
func (m *CircuitBreaker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CircuitBreaker.Marshal(b, m, deterministic)
}
func (m *CircuitBreaker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CircuitBreaker.Merge(m, src)
}
func (m *CircuitBreaker) XXX_Size() int {
	return xxx_messageInfo_CircuitBreaker.Size(m)
}
func (m *CircuitBreaker) XXX_DiscardUnknown() {
	xxx_messageInfo_CircuitBreaker.DiscardUnknown(m)
}

var xxx_messageInfo_CircuitBreaker proto.InternalMessageInfo

func (m *CircuitBreaker) GetSelector() *v1alpha1.Selector {
	if m != nil {
		return m.Selector
	}
	return nil
}

func (m *CircuitBreaker) GetConfig() *CircuitBreaker_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *CircuitBreaker) GetAction() *v1alpha11.FallbackAction {
	if m != nil {
		return m.Action
	}
	return nil
}

type CircuitBreaker_Config struct {
	// Types that are valid to be assigned to StrategyType:
	//	*CircuitBreaker_Config_SlowRequest_
	//	*CircuitBreaker_Config_ErrorRequest_
	StrategyType         isCircuitBreaker_Config_StrategyType `protobuf_oneof:"strategy_type"`
	AbnormalPercent      uint32                               `protobuf:"varint,3,opt,name=abnormal_percent,json=abnormalPercent,proto3" json:"abnormal_percent,omitempty"`
	Interval             *durationpb.Duration                 `protobuf:"bytes,4,opt,name=interval,proto3" json:"interval,omitempty"`
	BreakingInterval     *durationpb.Duration                 `protobuf:"bytes,5,opt,name=breaking_interval,json=breakingInterval,proto3" json:"breaking_interval,omitempty"`
	MinRequests          uint32                               `protobuf:"varint,6,opt,name=min_requests,json=minRequests,proto3" json:"min_requests,omitempty"`
	Recovery             *CircuitBreaker_Config_Recovery      `protobuf:"bytes,7,opt,name=recovery,proto3" json:"recovery,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *CircuitBreaker_Config) Reset()         { *m = CircuitBreaker_Config{} }
func (m *CircuitBreaker_Config) String() string { return proto.CompactTextString(m) }
func (*CircuitBreaker_Config) ProtoMessage()    {}
func (*CircuitBreaker_Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e7ca0736978053, []int{0, 0}
}

func (m *CircuitBreaker_Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CircuitBreaker_Config.Unmarshal(m, b)
}
func (m *CircuitBreaker_Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CircuitBreaker_Config.Marshal(b, m, deterministic)
}
func (m *CircuitBreaker_Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CircuitBreaker_Config.Merge(m, src)
}
func (m *CircuitBreaker_Config) XXX_Size() int {
	return xxx_messageInfo_CircuitBreaker_Config.Size(m)
}
func (m *CircuitBreaker_Config) XXX_DiscardUnknown() {
	xxx_messageInfo_CircuitBreaker_Config.DiscardUnknown(m)
}

var xxx_messageInfo_CircuitBreaker_Config proto.InternalMessageInfo

type isCircuitBreaker_Config_StrategyType interface {
	isCircuitBreaker_Config_StrategyType()
}

type CircuitBreaker_Config_SlowRequest_ struct {
	SlowRequest *CircuitBreaker_Config_SlowRequest `protobuf:"bytes,1,opt,name=slow_request,json=slowRequest,proto3,oneof"`
}

type CircuitBreaker_Config_ErrorRequest_ struct {
	ErrorRequest *CircuitBreaker_Config_ErrorRequest `protobuf:"bytes,2,opt,name=error_request,json=errorRequest,proto3,oneof"`
}

func (*CircuitBreaker_Config_SlowRequest_) isCircuitBreaker_Config_StrategyType() {}

func (*CircuitBreaker_Config_ErrorRequest_) isCircuitBreaker_Config_StrategyType() {}

func (m *CircuitBreaker_Config) GetStrategyType() isCircuitBreaker_Config_StrategyType {
	if m != nil {
		return m.StrategyType
	}
	return nil
}

func (m *CircuitBreaker_Config) GetSlowRequest() *CircuitBreaker_Config_SlowRequest {
	if x, ok := m.GetStrategyType().(*CircuitBreaker_Config_SlowRequest_); ok {
		return x.SlowRequest
	}
	return nil
}

func (m *CircuitBreaker_Config) GetErrorRequest() *CircuitBreaker_Config_ErrorRequest {
	if x, ok := m.GetStrategyType().(*CircuitBreaker_Config_ErrorRequest_); ok {
		return x.ErrorRequest
	}
	return nil
}

func (m *CircuitBreaker_Config) GetAbnormalPercent() uint32 {
	if m != nil {
		return m.AbnormalPercent
	}
	return 0
}

func (m *CircuitBreaker_Config) GetInterval() *durationpb.Duration {
	if m != nil {
		return m.Interval
	}
	return nil
}

func (m *CircuitBreaker_Config) GetBreakingInterval() *durationpb.Duration {
	if m != nil {
		return m.BreakingInterval
	}
	return nil
}

func (m *CircuitBreaker_Config) GetMinRequests() uint32 {
	if m != nil {
		return m.MinRequests
	}
	return 0
}

func (m *CircuitBreaker_Config) GetRecovery() *CircuitBreaker_Config_Recovery {
	if m != nil {
		return m.Recovery
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CircuitBreaker_Config) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CircuitBreaker_Config_SlowRequest_)(nil),
		(*CircuitBreaker_Config_ErrorRequest_)(nil),
	}
}

type CircuitBreaker_Config_SlowRequest struct {
	Latency              *durationpb.Duration `protobuf:"bytes,1,opt,name=latency,proto3" json:"latency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CircuitBreaker_Config_SlowRequest) Reset()         { *m = CircuitBreaker_Config_SlowRequest{} }
func (m *CircuitBreaker_Config_SlowRequest) String() string { return proto.CompactTextString(m) }
func (*CircuitBreaker_Config_SlowRequest) ProtoMessage()    {}
func (*CircuitBreaker_Config_SlowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e7ca0736978053, []int{0, 0, 0}
}

func (m *CircuitBreaker_Config_SlowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CircuitBreaker_Config_SlowRequest.Unmarshal(m, b)
}
func (m *CircuitBreaker_Config_SlowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CircuitBreaker_Config_SlowRequest.Marshal(b, m, deterministic)
}
func (m *CircuitBreaker_Config_SlowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CircuitBreaker_Config_SlowRequest.Merge(m, src)
}
func (m *CircuitBreaker_Config_SlowRequest) XXX_Size() int {
	return xxx_messageInfo_CircuitBreaker_Config_SlowRequest.Size(m)
}
func (m *CircuitBreaker_Config_SlowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CircuitBreaker_Config_SlowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CircuitBreaker_Config_SlowRequest proto.InternalMessageInfo

func (m *CircuitBreaker_Config_SlowRequest) GetLatency() *durationpb.Duration {
	if m != nil {
		return m.Latency
	}
	return nil
}

type CircuitBreaker_Config_ErrorRequest struct {
	// Or semantic
	Conditions           []string `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CircuitBreaker_Config_ErrorRequest) Reset()         { *m = CircuitBreaker_Config_ErrorRequest{} }
func (m *CircuitBreaker_Config_ErrorRequest) String() string { return proto.CompactTextString(m) }
func (*CircuitBreaker_Config_ErrorRequest) ProtoMessage()    {}
func (*CircuitBreaker_Config_ErrorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e7ca0736978053, []int{0, 0, 1}
}

func (m *CircuitBreaker_Config_ErrorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CircuitBreaker_Config_ErrorRequest.Unmarshal(m, b)
}
func (m *CircuitBreaker_Config_ErrorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CircuitBreaker_Config_ErrorRequest.Marshal(b, m, deterministic)
}
func (m *CircuitBreaker_Config_ErrorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CircuitBreaker_Config_ErrorRequest.Merge(m, src)
}
func (m *CircuitBreaker_Config_ErrorRequest) XXX_Size() int {
	return xxx_messageInfo_CircuitBreaker_Config_ErrorRequest.Size(m)
}
func (m *CircuitBreaker_Config_ErrorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CircuitBreaker_Config_ErrorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CircuitBreaker_Config_ErrorRequest proto.InternalMessageInfo

func (m *CircuitBreaker_Config_ErrorRequest) GetConditions() []string {
	if m != nil {
		return m.Conditions
	}
	return nil
}

type CircuitBreaker_Config_Recovery struct {
	ProbeCount           uint32   `protobuf:"varint,1,opt,name=probe_count,json=probeCount,proto3" json:"probe_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CircuitBreaker_Config_Recovery) Reset()         { *m = CircuitBreaker_Config_Recovery{} }
func (m *CircuitBreaker_Config_Recovery) String() string { return proto.CompactTextString(m) }
func (*CircuitBreaker_Config_Recovery) ProtoMessage()    {}
func (*CircuitBreaker_Config_Recovery) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e7ca0736978053, []int{0, 0, 2}
}

func (m *CircuitBreaker_Config_Recovery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CircuitBreaker_Config_Recovery.Unmarshal(m, b)
}
func (m *CircuitBreaker_Config_Recovery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CircuitBreaker_Config_Recovery.Marshal(b, m, deterministic)
}
func (m *CircuitBreaker_Config_Recovery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CircuitBreaker_Config_Recovery.Merge(m, src)
}
func (m *CircuitBreaker_Config_Recovery) XXX_Size() int {
	return xxx_messageInfo_CircuitBreaker_Config_Recovery.Size(m)
}
func (m *CircuitBreaker_Config_Recovery) XXX_DiscardUnknown() {
	xxx_messageInfo_CircuitBreaker_Config_Recovery.DiscardUnknown(m)
}

var xxx_messageInfo_CircuitBreaker_Config_Recovery proto.InternalMessageInfo

func (m *CircuitBreaker_Config_Recovery) GetProbeCount() uint32 {
	if m != nil {
		return m.ProbeCount
	}
	return 0
}

func init() {
	proto.RegisterType((*CircuitBreaker)(nil), "io.opensergo.policy.resilience.v1alpha1.CircuitBreaker")
	proto.RegisterType((*CircuitBreaker_Config)(nil), "io.opensergo.policy.resilience.v1alpha1.CircuitBreaker.Config")
	proto.RegisterType((*CircuitBreaker_Config_SlowRequest)(nil), "io.opensergo.policy.resilience.v1alpha1.CircuitBreaker.Config.SlowRequest")
	proto.RegisterType((*CircuitBreaker_Config_ErrorRequest)(nil), "io.opensergo.policy.resilience.v1alpha1.CircuitBreaker.Config.ErrorRequest")
	proto.RegisterType((*CircuitBreaker_Config_Recovery)(nil), "io.opensergo.policy.resilience.v1alpha1.CircuitBreaker.Config.Recovery")
}

func init() {
	proto.RegisterFile("policy/resilience/v1alpha1/circuit_breaker.proto", fileDescriptor_44e7ca0736978053)
}

var fileDescriptor_44e7ca0736978053 = []byte{
	// 518 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0x4d, 0x6f, 0xd3, 0x4e,
	0x10, 0xc6, 0xff, 0xfd, 0x97, 0xa6, 0x61, 0x92, 0xd0, 0xb2, 0x27, 0x63, 0xa1, 0x52, 0x10, 0x12,
	0x45, 0x85, 0x35, 0xa5, 0xe2, 0x8a, 0x20, 0x29, 0xe5, 0xed, 0x82, 0x5c, 0x89, 0x03, 0x17, 0x6b,
	0xbd, 0x9d, 0x9a, 0x55, 0x37, 0x3b, 0x66, 0xec, 0xa4, 0xca, 0xf7, 0xe3, 0x0b, 0xf0, 0x8d, 0x50,
	0xd6, 0x2f, 0x71, 0x25, 0xde, 0xa4, 0x1c, 0x77, 0x76, 0x9f, 0xdf, 0xf3, 0xcc, 0x78, 0x64, 0x78,
	0x96, 0x93, 0x35, 0x7a, 0x11, 0x31, 0x16, 0xc6, 0x1a, 0x74, 0x1a, 0xa3, 0xf9, 0x91, 0xb2, 0xf9,
	0x57, 0x75, 0x14, 0x69, 0xc3, 0x7a, 0x66, 0xca, 0x24, 0x65, 0x54, 0x97, 0xc8, 0x32, 0x67, 0x2a,
	0x49, 0x3c, 0x32, 0x24, 0x29, 0x47, 0x57, 0x20, 0x67, 0x24, 0x2b, 0xb9, 0x5c, 0xc9, 0x65, 0x23,
	0x0f, 0x03, 0x4d, 0xdc, 0xa5, 0x11, 0x63, 0x85, 0x08, 0xef, 0xd6, 0xa6, 0x9d, 0xbb, 0xe9, 0x94,
	0x5c, 0x7d, 0xbb, 0x97, 0x11, 0x65, 0x16, 0x23, 0x7f, 0x4a, 0x67, 0x17, 0xd1, 0xf9, 0x8c, 0x55,
	0x69, 0x9a, 0xfb, 0x07, 0xdf, 0xb7, 0xe1, 0xd6, 0xa4, 0x8a, 0x36, 0xae, 0x92, 0x89, 0x57, 0xd0,
	0x2f, 0xd0, 0xa2, 0x2e, 0x89, 0x83, 0x8d, 0xfd, 0x8d, 0x83, 0xc1, 0xf3, 0x87, 0xf2, 0x5a, 0x4c,
	0x6f, 0xde, 0xd8, 0xc9, 0xb3, 0xfa, 0x6d, 0xdc, 0xaa, 0xc4, 0x67, 0xe8, 0x69, 0x72, 0x17, 0x26,
	0x0b, 0xfe, 0xf7, 0xfa, 0x97, 0xf2, 0x1f, 0xdb, 0x94, 0xd7, 0xa3, 0xc8, 0x89, 0xa7, 0xc4, 0x35,
	0x4d, 0x9c, 0x40, 0x4f, 0xe9, 0x65, 0xf8, 0x60, 0xd3, 0x73, 0x9f, 0xfc, 0x92, 0xdb, 0xc2, 0x4e,
	0x95, 0xb5, 0xa9, 0xd2, 0x97, 0xaf, 0xbd, 0x26, 0xae, 0xb5, 0xe1, 0x8f, 0x2d, 0xe8, 0x55, 0x60,
	0x41, 0x30, 0x2c, 0x2c, 0x5d, 0x25, 0x8c, 0xdf, 0x66, 0x58, 0x94, 0x75, 0xbb, 0x1f, 0xd6, 0x8b,
	0x2b, 0xcf, 0x2c, 0x5d, 0xc5, 0x15, 0xf1, 0xdd, 0x7f, 0xf1, 0xa0, 0x58, 0x1d, 0x05, 0xc3, 0x08,
	0x99, 0x89, 0x5b, 0xc7, 0x6a, 0x40, 0x1f, 0xd7, 0x74, 0x7c, 0xb3, 0x64, 0xae, 0x2c, 0x87, 0xd8,
	0x39, 0x8b, 0xc7, 0xb0, 0xab, 0x52, 0x47, 0x3c, 0x55, 0x36, 0xc9, 0x91, 0x35, 0xba, 0xd2, 0xcf,
	0x6f, 0x14, 0xef, 0x34, 0xf5, 0x4f, 0x55, 0x59, 0xbc, 0x80, 0xbe, 0x71, 0x25, 0xf2, 0x5c, 0xd9,
	0xe0, 0x86, 0x4f, 0x76, 0x47, 0x56, 0x0b, 0x24, 0x9b, 0x05, 0x92, 0x27, 0xf5, 0x02, 0xc5, 0xed,
	0x53, 0x71, 0x0a, 0xb7, 0xfd, 0x5a, 0x1b, 0x97, 0x25, 0xad, 0x7e, 0xeb, 0x6f, 0xfa, 0xdd, 0x46,
	0xf3, 0xbe, 0xe1, 0xdc, 0x87, 0xe1, 0xd4, 0xb8, 0x66, 0x36, 0x45, 0xd0, 0xf3, 0x29, 0x07, 0x53,
	0xe3, 0xea, 0x5e, 0x0a, 0xa1, 0xa1, 0xcf, 0xa8, 0x69, 0x8e, 0xbc, 0x08, 0xb6, 0xbd, 0xc3, 0xdb,
	0x35, 0x67, 0x17, 0xd7, 0xb8, 0xb8, 0x05, 0x87, 0x63, 0x18, 0x74, 0xbe, 0xa1, 0x38, 0x86, 0x6d,
	0xab, 0x4a, 0x74, 0x7a, 0x51, 0x2f, 0xc8, 0x1f, 0x9a, 0x6a, 0x5e, 0x86, 0x12, 0x86, 0xdd, 0xaf,
	0x22, 0xf6, 0x00, 0x34, 0xb9, 0x73, 0xb3, 0x7c, 0x55, 0x04, 0x1b, 0xfb, 0x9b, 0x07, 0x37, 0xe3,
	0x4e, 0x25, 0x3c, 0x84, 0x7e, 0x93, 0x44, 0xdc, 0x83, 0x41, 0xce, 0x94, 0x62, 0xa2, 0x69, 0xe6,
	0xaa, 0xad, 0x1c, 0xc5, 0xe0, 0x4b, 0x93, 0x65, 0x65, 0xbc, 0x03, 0xa3, 0xa2, 0x64, 0x55, 0x62,
	0xb6, 0x48, 0xca, 0x45, 0x8e, 0xe3, 0xa7, 0x5f, 0x0e, 0x57, 0x23, 0x30, 0x14, 0xa9, 0xdc, 0x44,
	0xbf, 0xff, 0x19, 0xa5, 0x3d, 0x1f, 0xfc, 0xf8, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfe, 0xeb,
	0x73, 0x3d, 0xb1, 0x04, 0x00, 0x00,
}
