// Copyright 2023, OpenSergo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	trafficcontrolv1alpha1 "opensergo.io/api/client/pkg/apis/policy/trafficcontrol/v1alpha1"
	versioned "opensergo.io/api/client/pkg/clientset/versioned"
	internalinterfaces "opensergo.io/api/client/pkg/informers/externalversions/internalinterfaces"
	v1alpha1 "opensergo.io/api/client/pkg/listers/trafficcontrol/v1alpha1"
)

// RateLimitingInformer provides access to a shared informer and lister for
// RateLimitings.
type RateLimitingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.RateLimitingLister
}

type rateLimitingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRateLimitingInformer constructs a new informer for RateLimiting type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRateLimitingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRateLimitingInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRateLimitingInformer constructs a new informer for RateLimiting type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRateLimitingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TrafficcontrolV1alpha1().RateLimitings(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TrafficcontrolV1alpha1().RateLimitings(namespace).Watch(context.TODO(), options)
			},
		},
		&trafficcontrolv1alpha1.RateLimiting{},
		resyncPeriod,
		indexers,
	)
}

func (f *rateLimitingInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRateLimitingInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *rateLimitingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&trafficcontrolv1alpha1.RateLimiting{}, f.defaultInformer)
}

func (f *rateLimitingInformer) Lister() v1alpha1.RateLimitingLister {
	return v1alpha1.NewRateLimitingLister(f.Informer().GetIndexer())
}
