// Copyright 2023, OpenSergo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "opensergo.io/api/client/pkg/apis/policy/v1alpha1"
	scheme "opensergo.io/api/client/pkg/clientset/versioned/scheme"
)

// ConcurrencyLimitsGetter has a method to return a ConcurrencyLimitInterface.
// A group's client should implement this interface.
type ConcurrencyLimitsGetter interface {
	ConcurrencyLimits(namespace string) ConcurrencyLimitInterface
}

// ConcurrencyLimitInterface has methods to work with ConcurrencyLimit resources.
type ConcurrencyLimitInterface interface {
	Create(ctx context.Context, concurrencyLimit *v1alpha1.ConcurrencyLimit, opts v1.CreateOptions) (*v1alpha1.ConcurrencyLimit, error)
	Update(ctx context.Context, concurrencyLimit *v1alpha1.ConcurrencyLimit, opts v1.UpdateOptions) (*v1alpha1.ConcurrencyLimit, error)
	UpdateStatus(ctx context.Context, concurrencyLimit *v1alpha1.ConcurrencyLimit, opts v1.UpdateOptions) (*v1alpha1.ConcurrencyLimit, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ConcurrencyLimit, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ConcurrencyLimitList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ConcurrencyLimit, err error)
	ConcurrencyLimitExpansion
}

// concurrencyLimits implements ConcurrencyLimitInterface
type concurrencyLimits struct {
	client rest.Interface
	ns     string
}

// newConcurrencyLimits returns a ConcurrencyLimits
func newConcurrencyLimits(c *PolicyV1alpha1Client, namespace string) *concurrencyLimits {
	return &concurrencyLimits{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the concurrencyLimit, and returns the corresponding concurrencyLimit object, and an error if there is any.
func (c *concurrencyLimits) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ConcurrencyLimit, err error) {
	result = &v1alpha1.ConcurrencyLimit{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("concurrencylimits").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ConcurrencyLimits that match those selectors.
func (c *concurrencyLimits) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ConcurrencyLimitList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ConcurrencyLimitList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("concurrencylimits").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested concurrencyLimits.
func (c *concurrencyLimits) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("concurrencylimits").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a concurrencyLimit and creates it.  Returns the server's representation of the concurrencyLimit, and an error, if there is any.
func (c *concurrencyLimits) Create(ctx context.Context, concurrencyLimit *v1alpha1.ConcurrencyLimit, opts v1.CreateOptions) (result *v1alpha1.ConcurrencyLimit, err error) {
	result = &v1alpha1.ConcurrencyLimit{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("concurrencylimits").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(concurrencyLimit).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a concurrencyLimit and updates it. Returns the server's representation of the concurrencyLimit, and an error, if there is any.
func (c *concurrencyLimits) Update(ctx context.Context, concurrencyLimit *v1alpha1.ConcurrencyLimit, opts v1.UpdateOptions) (result *v1alpha1.ConcurrencyLimit, err error) {
	result = &v1alpha1.ConcurrencyLimit{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("concurrencylimits").
		Name(concurrencyLimit.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(concurrencyLimit).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *concurrencyLimits) UpdateStatus(ctx context.Context, concurrencyLimit *v1alpha1.ConcurrencyLimit, opts v1.UpdateOptions) (result *v1alpha1.ConcurrencyLimit, err error) {
	result = &v1alpha1.ConcurrencyLimit{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("concurrencylimits").
		Name(concurrencyLimit.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(concurrencyLimit).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the concurrencyLimit and deletes it. Returns an error if one occurs.
func (c *concurrencyLimits) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("concurrencylimits").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *concurrencyLimits) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("concurrencylimits").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched concurrencyLimit.
func (c *concurrencyLimits) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ConcurrencyLimit, err error) {
	result = &v1alpha1.ConcurrencyLimit{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("concurrencylimits").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
