// Code generated by protoc-gen-go. DO NOT EDIT.
// source: policy/v1alpha1/common.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Scope int32

const (
	// Single instance.
	Scope_LOCAL Scope = 0
	// The whole cluster.
	Scope_GLOBAL          Scope = 1
	Scope_GLOBAL_TO_LOCAL Scope = 2
)

var Scope_name = map[int32]string{
	0: "LOCAL",
	1: "GLOBAL",
	2: "GLOBAL_TO_LOCAL",
}

var Scope_value = map[string]int32{
	"LOCAL":           0,
	"GLOBAL":          1,
	"GLOBAL_TO_LOCAL": 2,
}

func (x Scope) String() string {
	return proto.EnumName(Scope_name, int32(x))
}

func (Scope) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_895fb471204726b8, []int{0}
}

type FallbackAction_HTTPFallback_HTTPCustomResponse_BodyEncoding int32

const (
	FallbackAction_HTTPFallback_HTTPCustomResponse_TEXT FallbackAction_HTTPFallback_HTTPCustomResponse_BodyEncoding = 0
	FallbackAction_HTTPFallback_HTTPCustomResponse_JSON FallbackAction_HTTPFallback_HTTPCustomResponse_BodyEncoding = 1
)

var FallbackAction_HTTPFallback_HTTPCustomResponse_BodyEncoding_name = map[int32]string{
	0: "TEXT",
	1: "JSON",
}

var FallbackAction_HTTPFallback_HTTPCustomResponse_BodyEncoding_value = map[string]int32{
	"TEXT": 0,
	"JSON": 1,
}

func (x FallbackAction_HTTPFallback_HTTPCustomResponse_BodyEncoding) String() string {
	return proto.EnumName(FallbackAction_HTTPFallback_HTTPCustomResponse_BodyEncoding_name, int32(x))
}

func (FallbackAction_HTTPFallback_HTTPCustomResponse_BodyEncoding) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_895fb471204726b8, []int{0, 0, 0, 0}
}

type FallbackAction struct {
	// Types that are valid to be assigned to FallbackType:
	//	*FallbackAction_Http
	FallbackType         isFallbackAction_FallbackType `protobuf_oneof:"fallback_type"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *FallbackAction) Reset()         { *m = FallbackAction{} }
func (m *FallbackAction) String() string { return proto.CompactTextString(m) }
func (*FallbackAction) ProtoMessage()    {}
func (*FallbackAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_895fb471204726b8, []int{0}
}

func (m *FallbackAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FallbackAction.Unmarshal(m, b)
}
func (m *FallbackAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FallbackAction.Marshal(b, m, deterministic)
}
func (m *FallbackAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FallbackAction.Merge(m, src)
}
func (m *FallbackAction) XXX_Size() int {
	return xxx_messageInfo_FallbackAction.Size(m)
}
func (m *FallbackAction) XXX_DiscardUnknown() {
	xxx_messageInfo_FallbackAction.DiscardUnknown(m)
}

var xxx_messageInfo_FallbackAction proto.InternalMessageInfo

type isFallbackAction_FallbackType interface {
	isFallbackAction_FallbackType()
}

type FallbackAction_Http struct {
	Http *FallbackAction_HTTPFallback `protobuf:"bytes,1,opt,name=http,proto3,oneof"`
}

func (*FallbackAction_Http) isFallbackAction_FallbackType() {}

func (m *FallbackAction) GetFallbackType() isFallbackAction_FallbackType {
	if m != nil {
		return m.FallbackType
	}
	return nil
}

func (m *FallbackAction) GetHttp() *FallbackAction_HTTPFallback {
	if x, ok := m.GetFallbackType().(*FallbackAction_Http); ok {
		return x.Http
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FallbackAction) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FallbackAction_Http)(nil),
	}
}

type FallbackAction_HTTPFallback struct {
	// Types that are valid to be assigned to ActionType:
	//	*FallbackAction_HTTPFallback_CustomResponse
	//	*FallbackAction_HTTPFallback_Redirect
	ActionType           isFallbackAction_HTTPFallback_ActionType `protobuf_oneof:"action_type"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *FallbackAction_HTTPFallback) Reset()         { *m = FallbackAction_HTTPFallback{} }
func (m *FallbackAction_HTTPFallback) String() string { return proto.CompactTextString(m) }
func (*FallbackAction_HTTPFallback) ProtoMessage()    {}
func (*FallbackAction_HTTPFallback) Descriptor() ([]byte, []int) {
	return fileDescriptor_895fb471204726b8, []int{0, 0}
}

func (m *FallbackAction_HTTPFallback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FallbackAction_HTTPFallback.Unmarshal(m, b)
}
func (m *FallbackAction_HTTPFallback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FallbackAction_HTTPFallback.Marshal(b, m, deterministic)
}
func (m *FallbackAction_HTTPFallback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FallbackAction_HTTPFallback.Merge(m, src)
}
func (m *FallbackAction_HTTPFallback) XXX_Size() int {
	return xxx_messageInfo_FallbackAction_HTTPFallback.Size(m)
}
func (m *FallbackAction_HTTPFallback) XXX_DiscardUnknown() {
	xxx_messageInfo_FallbackAction_HTTPFallback.DiscardUnknown(m)
}

var xxx_messageInfo_FallbackAction_HTTPFallback proto.InternalMessageInfo

type isFallbackAction_HTTPFallback_ActionType interface {
	isFallbackAction_HTTPFallback_ActionType()
}

type FallbackAction_HTTPFallback_CustomResponse struct {
	CustomResponse *FallbackAction_HTTPFallback_HTTPCustomResponse `protobuf:"bytes,1,opt,name=custom_response,json=customResponse,proto3,oneof"`
}

type FallbackAction_HTTPFallback_Redirect struct {
	Redirect *FallbackAction_HTTPFallback_HTTPRedirect `protobuf:"bytes,2,opt,name=redirect,proto3,oneof"`
}

func (*FallbackAction_HTTPFallback_CustomResponse) isFallbackAction_HTTPFallback_ActionType() {}

func (*FallbackAction_HTTPFallback_Redirect) isFallbackAction_HTTPFallback_ActionType() {}

func (m *FallbackAction_HTTPFallback) GetActionType() isFallbackAction_HTTPFallback_ActionType {
	if m != nil {
		return m.ActionType
	}
	return nil
}

func (m *FallbackAction_HTTPFallback) GetCustomResponse() *FallbackAction_HTTPFallback_HTTPCustomResponse {
	if x, ok := m.GetActionType().(*FallbackAction_HTTPFallback_CustomResponse); ok {
		return x.CustomResponse
	}
	return nil
}

func (m *FallbackAction_HTTPFallback) GetRedirect() *FallbackAction_HTTPFallback_HTTPRedirect {
	if x, ok := m.GetActionType().(*FallbackAction_HTTPFallback_Redirect); ok {
		return x.Redirect
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FallbackAction_HTTPFallback) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FallbackAction_HTTPFallback_CustomResponse)(nil),
		(*FallbackAction_HTTPFallback_Redirect)(nil),
	}
}

type FallbackAction_HTTPFallback_HTTPCustomResponse struct {
	StatusCode           uint32                                                      `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	BodyEncoding         FallbackAction_HTTPFallback_HTTPCustomResponse_BodyEncoding `protobuf:"varint,2,opt,name=body_encoding,json=bodyEncoding,proto3,enum=io.opensergo.policy.v1alpha1.FallbackAction_HTTPFallback_HTTPCustomResponse_BodyEncoding" json:"body_encoding,omitempty"`
	Body                 string                                                      `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	ResponseHeadersToAdd map[string]string                                           `protobuf:"bytes,4,rep,name=response_headers_to_add,json=responseHeadersToAdd,proto3" json:"response_headers_to_add,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                                    `json:"-"`
	XXX_unrecognized     []byte                                                      `json:"-"`
	XXX_sizecache        int32                                                       `json:"-"`
}

func (m *FallbackAction_HTTPFallback_HTTPCustomResponse) Reset() {
	*m = FallbackAction_HTTPFallback_HTTPCustomResponse{}
}
func (m *FallbackAction_HTTPFallback_HTTPCustomResponse) String() string {
	return proto.CompactTextString(m)
}
func (*FallbackAction_HTTPFallback_HTTPCustomResponse) ProtoMessage() {}
func (*FallbackAction_HTTPFallback_HTTPCustomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_895fb471204726b8, []int{0, 0, 0}
}

func (m *FallbackAction_HTTPFallback_HTTPCustomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FallbackAction_HTTPFallback_HTTPCustomResponse.Unmarshal(m, b)
}
func (m *FallbackAction_HTTPFallback_HTTPCustomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FallbackAction_HTTPFallback_HTTPCustomResponse.Marshal(b, m, deterministic)
}
func (m *FallbackAction_HTTPFallback_HTTPCustomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FallbackAction_HTTPFallback_HTTPCustomResponse.Merge(m, src)
}
func (m *FallbackAction_HTTPFallback_HTTPCustomResponse) XXX_Size() int {
	return xxx_messageInfo_FallbackAction_HTTPFallback_HTTPCustomResponse.Size(m)
}
func (m *FallbackAction_HTTPFallback_HTTPCustomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FallbackAction_HTTPFallback_HTTPCustomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FallbackAction_HTTPFallback_HTTPCustomResponse proto.InternalMessageInfo

func (m *FallbackAction_HTTPFallback_HTTPCustomResponse) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *FallbackAction_HTTPFallback_HTTPCustomResponse) GetBodyEncoding() FallbackAction_HTTPFallback_HTTPCustomResponse_BodyEncoding {
	if m != nil {
		return m.BodyEncoding
	}
	return FallbackAction_HTTPFallback_HTTPCustomResponse_TEXT
}

func (m *FallbackAction_HTTPFallback_HTTPCustomResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *FallbackAction_HTTPFallback_HTTPCustomResponse) GetResponseHeadersToAdd() map[string]string {
	if m != nil {
		return m.ResponseHeadersToAdd
	}
	return nil
}

type FallbackAction_HTTPFallback_HTTPRedirect struct {
	RedirectUrl          string   `protobuf:"bytes,1,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FallbackAction_HTTPFallback_HTTPRedirect) Reset() {
	*m = FallbackAction_HTTPFallback_HTTPRedirect{}
}
func (m *FallbackAction_HTTPFallback_HTTPRedirect) String() string { return proto.CompactTextString(m) }
func (*FallbackAction_HTTPFallback_HTTPRedirect) ProtoMessage()    {}
func (*FallbackAction_HTTPFallback_HTTPRedirect) Descriptor() ([]byte, []int) {
	return fileDescriptor_895fb471204726b8, []int{0, 0, 1}
}

func (m *FallbackAction_HTTPFallback_HTTPRedirect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FallbackAction_HTTPFallback_HTTPRedirect.Unmarshal(m, b)
}
func (m *FallbackAction_HTTPFallback_HTTPRedirect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FallbackAction_HTTPFallback_HTTPRedirect.Marshal(b, m, deterministic)
}
func (m *FallbackAction_HTTPFallback_HTTPRedirect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FallbackAction_HTTPFallback_HTTPRedirect.Merge(m, src)
}
func (m *FallbackAction_HTTPFallback_HTTPRedirect) XXX_Size() int {
	return xxx_messageInfo_FallbackAction_HTTPFallback_HTTPRedirect.Size(m)
}
func (m *FallbackAction_HTTPFallback_HTTPRedirect) XXX_DiscardUnknown() {
	xxx_messageInfo_FallbackAction_HTTPFallback_HTTPRedirect.DiscardUnknown(m)
}

var xxx_messageInfo_FallbackAction_HTTPFallback_HTTPRedirect proto.InternalMessageInfo

func (m *FallbackAction_HTTPFallback_HTTPRedirect) GetRedirectUrl() string {
	if m != nil {
		return m.RedirectUrl
	}
	return ""
}

func init() {
	proto.RegisterEnum("io.opensergo.policy.v1alpha1.Scope", Scope_name, Scope_value)
	proto.RegisterEnum("io.opensergo.policy.v1alpha1.FallbackAction_HTTPFallback_HTTPCustomResponse_BodyEncoding", FallbackAction_HTTPFallback_HTTPCustomResponse_BodyEncoding_name, FallbackAction_HTTPFallback_HTTPCustomResponse_BodyEncoding_value)
	proto.RegisterType((*FallbackAction)(nil), "io.opensergo.policy.v1alpha1.FallbackAction")
	proto.RegisterType((*FallbackAction_HTTPFallback)(nil), "io.opensergo.policy.v1alpha1.FallbackAction.HTTPFallback")
	proto.RegisterType((*FallbackAction_HTTPFallback_HTTPCustomResponse)(nil), "io.opensergo.policy.v1alpha1.FallbackAction.HTTPFallback.HTTPCustomResponse")
	proto.RegisterMapType((map[string]string)(nil), "io.opensergo.policy.v1alpha1.FallbackAction.HTTPFallback.HTTPCustomResponse.ResponseHeadersToAddEntry")
	proto.RegisterType((*FallbackAction_HTTPFallback_HTTPRedirect)(nil), "io.opensergo.policy.v1alpha1.FallbackAction.HTTPFallback.HTTPRedirect")
}

func init() { proto.RegisterFile("policy/v1alpha1/common.proto", fileDescriptor_895fb471204726b8) }

var fileDescriptor_895fb471204726b8 = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0xf3, 0xa5, 0x66, 0xf2, 0xa9, 0xa5, 0x12, 0x21, 0xaa, 0x44, 0xc8, 0x29, 0xe2, 0xe0,
	0x28, 0xe9, 0x05, 0xb8, 0x25, 0x51, 0xda, 0x08, 0x45, 0x18, 0x6d, 0x8d, 0x04, 0x5c, 0xac, 0xcd,
	0xee, 0xb6, 0xb1, 0xea, 0x78, 0xac, 0xf5, 0xa6, 0xc8, 0x17, 0xce, 0xfc, 0x09, 0xfe, 0x16, 0xff,
	0x06, 0x09, 0x65, 0x6d, 0x97, 0x94, 0xaf, 0x03, 0xed, 0x6d, 0xe6, 0xed, 0xcc, 0x7b, 0x33, 0x6f,
	0x12, 0xc3, 0x49, 0x84, 0x81, 0xcf, 0x93, 0xd1, 0xcd, 0x98, 0x05, 0xd1, 0x86, 0x8d, 0x47, 0x1c,
	0xb7, 0x5b, 0x0c, 0xed, 0x48, 0xa1, 0x46, 0x72, 0xe2, 0xa3, 0x8d, 0x91, 0x0c, 0x63, 0xa9, 0xae,
	0xd0, 0x4e, 0x4b, 0xed, 0xbc, 0x74, 0xf0, 0xbd, 0x0a, 0xad, 0x33, 0x16, 0x04, 0x6b, 0xc6, 0xaf,
	0xa7, 0x5c, 0xfb, 0x18, 0x12, 0x07, 0xca, 0x1b, 0xad, 0xa3, 0xae, 0xd5, 0xb7, 0x86, 0xf5, 0xc9,
	0x4b, 0xfb, 0x5f, 0xfd, 0xf6, 0xdd, 0x5e, 0x7b, 0xe9, 0xba, 0x6f, 0x73, 0x68, 0x59, 0xa0, 0x86,
	0xa8, 0xf7, 0xa5, 0x0a, 0x8d, 0xc3, 0x07, 0xf2, 0x09, 0xda, 0x7c, 0x17, 0x6b, 0xdc, 0x7a, 0x4a,
	0xc6, 0x11, 0x86, 0xb1, 0xcc, 0xc4, 0x56, 0xff, 0x2d, 0x66, 0x92, 0xb9, 0x21, 0xa5, 0x19, 0xe7,
	0xb2, 0x40, 0x5b, 0xfc, 0x0e, 0x42, 0x04, 0x1c, 0x29, 0x29, 0x7c, 0x25, 0xb9, 0xee, 0x16, 0x8d,
	0xe2, 0xd9, 0xfd, 0x14, 0x69, 0xc6, 0xb6, 0x2c, 0xd0, 0x5b, 0xe6, 0xde, 0xb7, 0x12, 0x90, 0xdf,
	0xc7, 0x21, 0x4f, 0xa1, 0x1e, 0x6b, 0xa6, 0x77, 0xb1, 0xc7, 0x51, 0xa4, 0x1b, 0x37, 0x29, 0xa4,
	0xd0, 0x1c, 0x85, 0x24, 0x9f, 0xa1, 0xb9, 0x46, 0x91, 0x78, 0x32, 0xe4, 0x28, 0xfc, 0xf0, 0xca,
	0x8c, 0xd8, 0x9a, 0x7c, 0x78, 0x48, 0x53, 0xec, 0x19, 0x8a, 0x64, 0x91, 0x09, 0xd0, 0xc6, 0xfa,
	0x20, 0x23, 0x04, 0xca, 0xfb, 0xbc, 0x5b, 0xea, 0x5b, 0xc3, 0x1a, 0x35, 0x31, 0xf9, 0x6a, 0xc1,
	0xe3, 0xfc, 0x48, 0xde, 0x46, 0x32, 0x21, 0x55, 0xec, 0x69, 0xf4, 0x98, 0x10, 0xdd, 0x72, 0xbf,
	0x34, 0xac, 0x4f, 0x2e, 0x1f, 0x74, 0xbc, 0xdb, 0xe3, 0xa5, 0x52, 0x2e, 0x4e, 0x85, 0x58, 0x84,
	0x5a, 0x25, 0xf4, 0x58, 0xfd, 0xe1, 0xa9, 0x77, 0x0e, 0x4f, 0xfe, 0xda, 0x42, 0x3a, 0x50, 0xba,
	0x96, 0x89, 0x71, 0xba, 0x46, 0xf7, 0x21, 0x39, 0x86, 0xca, 0x0d, 0x0b, 0x76, 0xd2, 0x58, 0x5b,
	0xa3, 0x69, 0xf2, 0xaa, 0xf8, 0xc2, 0x1a, 0x0c, 0xa0, 0x71, 0x68, 0x0d, 0x39, 0x82, 0xb2, 0xbb,
	0x78, 0xef, 0x76, 0x0a, 0xfb, 0xe8, 0xf5, 0x85, 0xf3, 0xa6, 0x63, 0xf5, 0xc6, 0xe9, 0xef, 0x38,
	0x3f, 0x3a, 0x79, 0x06, 0x8d, 0xfc, 0xe8, 0xde, 0x4e, 0x05, 0x99, 0x50, 0x3d, 0xc7, 0xde, 0xa9,
	0x60, 0xd6, 0x84, 0x3a, 0x33, 0x9b, 0x7b, 0x3a, 0x89, 0xe4, 0xac, 0x0d, 0xcd, 0xcb, 0x6c, 0x7b,
	0x03, 0x3c, 0x3f, 0x85, 0xca, 0x05, 0xc7, 0x48, 0x92, 0x1a, 0x54, 0x56, 0xce, 0x7c, 0xba, 0xea,
	0x14, 0x08, 0x40, 0xf5, 0x7c, 0xe5, 0xcc, 0xa6, 0xab, 0x8e, 0x45, 0x1e, 0x41, 0x3b, 0x8d, 0x3d,
	0xd7, 0xf1, 0xd2, 0x82, 0xe2, 0x6c, 0xf0, 0xb1, 0xff, 0xd3, 0x70, 0x1f, 0x47, 0x2c, 0xf2, 0x47,
	0xbf, 0x7c, 0x03, 0xd6, 0x55, 0xf3, 0xef, 0x3f, 0xfd, 0x11, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x79,
	0x0c, 0x69, 0x1d, 0x04, 0x00, 0x00,
}
