// Code generated by protoc-gen-deepcopy. DO NOT EDIT.

package v1alpha1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using ConcurrencyLimit within kubernetes types, where deepcopy-gen is used.
func (in *ConcurrencyLimit) DeepCopyInto(out *ConcurrencyLimit) {
	p := proto.Clone(in).(*ConcurrencyLimit)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConcurrencyLimit. Required by controller-gen.
func (in *ConcurrencyLimit) DeepCopy() *ConcurrencyLimit {
	if in == nil {
		return nil
	}
	out := new(ConcurrencyLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ConcurrencyLimit. Required by controller-gen.
func (in *ConcurrencyLimit) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
