// Code generated by protoc-gen-go. DO NOT EDIT.
// source: policy/v1alpha1/concurrency_limiting.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	v1alpha1 "opensergo.io/api/core/v1alpha1"
	_ "opensergo.io/api/policy/trafficcontrol/v1alpha1"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// <!-- crd generation tags
// +cue-gen:ConcurrencyLimiting:groupName:policy.opensergo.io
// +cue-gen:ConcurrencyLimiting:version:v1alpha1
// +cue-gen:ConcurrencyLimiting:annotations:helm.sh/resource-policy=keep
// +cue-gen:ConcurrencyLimiting:subresource:status
// +cue-gen:ConcurrencyLimiting:scope:Namespaced
// +cue-gen:ConcurrencyLimiting:resource:categories=opensergo-io
// +cue-gen:ConcurrencyLimiting:preserveUnknownFields:false
// -->
//
// <!-- go code generation tags
// +kubetype-gen
// +kubetype-gen:groupVersion=policy.opensergo.io/v1alpha1
// +genclient
// +k8s:deepcopy-gen=true
// -->
type ConcurrencyLimiting struct {
	Selector *v1alpha1.Selector `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	// The config for concurrency limiting.
	Config *ConcurrencyLimiting_Config `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	// The fallback action when the concurrency limiting works.
	Action               *FallbackAction `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ConcurrencyLimiting) Reset()         { *m = ConcurrencyLimiting{} }
func (m *ConcurrencyLimiting) String() string { return proto.CompactTextString(m) }
func (*ConcurrencyLimiting) ProtoMessage()    {}
func (*ConcurrencyLimiting) Descriptor() ([]byte, []int) {
	return fileDescriptor_4008425b8734b605, []int{0}
}

func (m *ConcurrencyLimiting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConcurrencyLimiting.Unmarshal(m, b)
}
func (m *ConcurrencyLimiting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConcurrencyLimiting.Marshal(b, m, deterministic)
}
func (m *ConcurrencyLimiting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConcurrencyLimiting.Merge(m, src)
}
func (m *ConcurrencyLimiting) XXX_Size() int {
	return xxx_messageInfo_ConcurrencyLimiting.Size(m)
}
func (m *ConcurrencyLimiting) XXX_DiscardUnknown() {
	xxx_messageInfo_ConcurrencyLimiting.DiscardUnknown(m)
}

var xxx_messageInfo_ConcurrencyLimiting proto.InternalMessageInfo

func (m *ConcurrencyLimiting) GetSelector() *v1alpha1.Selector {
	if m != nil {
		return m.Selector
	}
	return nil
}

func (m *ConcurrencyLimiting) GetConfig() *ConcurrencyLimiting_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *ConcurrencyLimiting) GetAction() *FallbackAction {
	if m != nil {
		return m.Action
	}
	return nil
}

type ConcurrencyLimiting_Config struct {
	Scope                Scope    `protobuf:"varint,1,opt,name=scope,proto3,enum=io.opensergo.policy.v1alpha1.Scope" json:"scope,omitempty"`
	MaxConcurrency       uint64   `protobuf:"varint,2,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConcurrencyLimiting_Config) Reset()         { *m = ConcurrencyLimiting_Config{} }
func (m *ConcurrencyLimiting_Config) String() string { return proto.CompactTextString(m) }
func (*ConcurrencyLimiting_Config) ProtoMessage()    {}
func (*ConcurrencyLimiting_Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_4008425b8734b605, []int{0, 0}
}

func (m *ConcurrencyLimiting_Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConcurrencyLimiting_Config.Unmarshal(m, b)
}
func (m *ConcurrencyLimiting_Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConcurrencyLimiting_Config.Marshal(b, m, deterministic)
}
func (m *ConcurrencyLimiting_Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConcurrencyLimiting_Config.Merge(m, src)
}
func (m *ConcurrencyLimiting_Config) XXX_Size() int {
	return xxx_messageInfo_ConcurrencyLimiting_Config.Size(m)
}
func (m *ConcurrencyLimiting_Config) XXX_DiscardUnknown() {
	xxx_messageInfo_ConcurrencyLimiting_Config.DiscardUnknown(m)
}

var xxx_messageInfo_ConcurrencyLimiting_Config proto.InternalMessageInfo

func (m *ConcurrencyLimiting_Config) GetScope() Scope {
	if m != nil {
		return m.Scope
	}
	return Scope_LOCAL
}

func (m *ConcurrencyLimiting_Config) GetMaxConcurrency() uint64 {
	if m != nil {
		return m.MaxConcurrency
	}
	return 0
}

func init() {
	proto.RegisterType((*ConcurrencyLimiting)(nil), "io.opensergo.policy.v1alpha1.ConcurrencyLimiting")
	proto.RegisterType((*ConcurrencyLimiting_Config)(nil), "io.opensergo.policy.v1alpha1.ConcurrencyLimiting.Config")
}

func init() {
	proto.RegisterFile("policy/v1alpha1/concurrency_limiting.proto", fileDescriptor_4008425b8734b605)
}

var fileDescriptor_4008425b8734b605 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4d, 0x4b, 0x03, 0x31,
	0x10, 0x86, 0x69, 0xd5, 0x45, 0x22, 0x54, 0x88, 0x97, 0xa5, 0xf4, 0x50, 0xaa, 0xa0, 0xa8, 0x64,
	0x69, 0xbd, 0xe8, 0xcd, 0x2f, 0x3c, 0x79, 0x90, 0xed, 0xcd, 0x4b, 0x49, 0x87, 0xec, 0x3a, 0x98,
	0xcd, 0x84, 0x34, 0x4a, 0xfb, 0x63, 0xfd, 0x2f, 0xd2, 0x6c, 0x6a, 0xab, 0x96, 0xbd, 0x66, 0xe6,
	0x79, 0xf2, 0xbe, 0x0c, 0x3b, 0xb7, 0xa4, 0x11, 0x16, 0xd9, 0xe7, 0x50, 0x6a, 0xfb, 0x26, 0x87,
	0x19, 0x90, 0x81, 0x0f, 0xe7, 0x94, 0x81, 0xc5, 0x44, 0x63, 0x85, 0x1e, 0x4d, 0x29, 0xac, 0x23,
	0x4f, 0xbc, 0x87, 0x24, 0xc8, 0x2a, 0x33, 0x53, 0xae, 0x24, 0x51, 0x83, 0x62, 0x05, 0x76, 0x53,
	0x20, 0xa7, 0x36, 0x3d, 0x4e, 0xd5, 0x5c, 0xb7, 0xf7, 0xff, 0x8f, 0xaa, 0x22, 0x13, 0xa7, 0x17,
	0x71, 0xea, 0x9d, 0x2c, 0x0a, 0x04, 0x20, 0xe3, 0x1d, 0xe9, 0xed, 0xcb, 0x83, 0xaf, 0x36, 0x3b,
	0x7a, 0x58, 0x27, 0x7c, 0x8e, 0x01, 0xf9, 0x2d, 0xdb, 0x9f, 0x29, 0xad, 0xc0, 0x93, 0x4b, 0x5b,
	0xfd, 0xd6, 0xd9, 0xc1, 0xe8, 0x44, 0xfc, 0x4a, 0x1b, 0xe2, 0xac, 0x9c, 0x62, 0x1c, 0x77, 0xf3,
	0x1f, 0x8a, 0xbf, 0xb0, 0x04, 0xc8, 0x14, 0x58, 0xa6, 0xed, 0xc0, 0x5f, 0x8b, 0xa6, 0xb6, 0x62,
	0x4b, 0x88, 0xe5, 0x5b, 0x81, 0x65, 0x1e, 0x3d, 0xfc, 0x91, 0x25, 0x12, 0x3c, 0x92, 0x49, 0x77,
	0x82, 0xf1, 0xb2, 0xd9, 0xf8, 0x24, 0xb5, 0x9e, 0x4a, 0x78, 0xbf, 0x0b, 0x4c, 0x1e, 0xd9, 0xae,
	0x66, 0x49, 0xed, 0xe5, 0x37, 0x6c, 0x6f, 0x06, 0x64, 0x55, 0x28, 0xd8, 0x19, 0x1d, 0x37, 0xeb,
	0xc6, 0xcb, 0xd5, 0xbc, 0x26, 0xf8, 0x29, 0x3b, 0xac, 0xe4, 0x7c, 0xb2, 0x71, 0xdb, 0xd0, 0x72,
	0x37, 0xef, 0x54, 0x72, 0xbe, 0x51, 0xe5, 0x7e, 0xf0, 0xda, 0x5f, 0x2b, 0x91, 0x32, 0x69, 0x31,
	0xfb, 0x73, 0xbd, 0x69, 0x12, 0x4e, 0x71, 0xf5, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x06, 0x8b,
	0x01, 0x3b, 0x02, 0x00, 0x00,
}
