// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for ConcurrencyLimit
func (this *ConcurrencyLimit) MarshalJSON() ([]byte, error) {
	str, err := ConcurrencyLimitMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ConcurrencyLimit
func (this *ConcurrencyLimit) UnmarshalJSON(b []byte) error {
	return ConcurrencyLimitUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ConcurrencyLimit_Config
func (this *ConcurrencyLimit_Config) MarshalJSON() ([]byte, error) {
	str, err := ConcurrencyLimitMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ConcurrencyLimit_Config
func (this *ConcurrencyLimit_Config) UnmarshalJSON(b []byte) error {
	return ConcurrencyLimitUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	ConcurrencyLimitMarshaler   = &jsonpb.Marshaler{}
	ConcurrencyLimitUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
