// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for ConcurrencyLimiting
func (this *ConcurrencyLimiting) MarshalJSON() ([]byte, error) {
	str, err := ConcurrencyLimitingMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ConcurrencyLimiting
func (this *ConcurrencyLimiting) UnmarshalJSON(b []byte) error {
	return ConcurrencyLimitingUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ConcurrencyLimiting_Config
func (this *ConcurrencyLimiting_Config) MarshalJSON() ([]byte, error) {
	str, err := ConcurrencyLimitingMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ConcurrencyLimiting_Config
func (this *ConcurrencyLimiting_Config) UnmarshalJSON(b []byte) error {
	return ConcurrencyLimitingUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	ConcurrencyLimitingMarshaler   = &jsonpb.Marshaler{}
	ConcurrencyLimitingUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
