// Code generated by protoc-gen-deepcopy. DO NOT EDIT.

package v1alpha1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using ConcurrencyLimiting within kubernetes types, where deepcopy-gen is used.
func (in *ConcurrencyLimiting) DeepCopyInto(out *ConcurrencyLimiting) {
	p := proto.Clone(in).(*ConcurrencyLimiting)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConcurrencyLimiting. Required by controller-gen.
func (in *ConcurrencyLimiting) DeepCopy() *ConcurrencyLimiting {
	if in == nil {
		return nil
	}
	out := new(ConcurrencyLimiting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ConcurrencyLimiting. Required by controller-gen.
func (in *ConcurrencyLimiting) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
