// Code generated by protoc-gen-go. DO NOT EDIT.
// source: policy/v1alpha1/rate_limiting.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	math "math"
	v1alpha1 "opensergo.io/api/core/v1alpha1"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// <!-- crd generation tags
// +cue-gen:RateLimiting:groupName:policy.opensergo.io
// +cue-gen:RateLimiting:version:v1alpha1
// +cue-gen:RateLimiting:annotations:helm.sh/resource-policy=keep
// +cue-gen:RateLimiting:subresource:status
// +cue-gen:RateLimiting:scope:Namespaced
// +cue-gen:RateLimiting:resource:categories=opensergo-io
// +cue-gen:RateLimiting:preserveUnknownFields:false
// -->
//
// <!-- go code generation tags
// +kubetype-gen
// +kubetype-gen:groupVersion=policy.opensergo.io/v1alpha1
// +genclient
// +k8s:deepcopy-gen=true
// -->
type RateLimiting struct {
	Selector *v1alpha1.Selector `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	// The config for rate limiting.
	Config *RateLimiting_Config `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	// The fallback action when the rate limiting works.
	Action               *FallbackAction `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RateLimiting) Reset()         { *m = RateLimiting{} }
func (m *RateLimiting) String() string { return proto.CompactTextString(m) }
func (*RateLimiting) ProtoMessage()    {}
func (*RateLimiting) Descriptor() ([]byte, []int) {
	return fileDescriptor_52e97190637d71c6, []int{0}
}

func (m *RateLimiting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateLimiting.Unmarshal(m, b)
}
func (m *RateLimiting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateLimiting.Marshal(b, m, deterministic)
}
func (m *RateLimiting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateLimiting.Merge(m, src)
}
func (m *RateLimiting) XXX_Size() int {
	return xxx_messageInfo_RateLimiting.Size(m)
}
func (m *RateLimiting) XXX_DiscardUnknown() {
	xxx_messageInfo_RateLimiting.DiscardUnknown(m)
}

var xxx_messageInfo_RateLimiting proto.InternalMessageInfo

func (m *RateLimiting) GetSelector() *v1alpha1.Selector {
	if m != nil {
		return m.Selector
	}
	return nil
}

func (m *RateLimiting) GetConfig() *RateLimiting_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *RateLimiting) GetAction() *FallbackAction {
	if m != nil {
		return m.Action
	}
	return nil
}

type RateLimiting_Config struct {
	Scope Scope `protobuf:"varint,1,opt,name=scope,proto3,enum=io.opensergo.policy.v1alpha1.Scope" json:"scope,omitempty"`
	// The max requests can pass within the window.
	Limit uint64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// The max requests can pass instantly.
	Burst uint64 `protobuf:"varint,3,opt,name=burst,proto3" json:"burst,omitempty"`
	// The window in which the max requests can pass
	Interval             *durationpb.Duration `protobuf:"bytes,4,opt,name=interval,proto3" json:"interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RateLimiting_Config) Reset()         { *m = RateLimiting_Config{} }
func (m *RateLimiting_Config) String() string { return proto.CompactTextString(m) }
func (*RateLimiting_Config) ProtoMessage()    {}
func (*RateLimiting_Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_52e97190637d71c6, []int{0, 0}
}

func (m *RateLimiting_Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateLimiting_Config.Unmarshal(m, b)
}
func (m *RateLimiting_Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateLimiting_Config.Marshal(b, m, deterministic)
}
func (m *RateLimiting_Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateLimiting_Config.Merge(m, src)
}
func (m *RateLimiting_Config) XXX_Size() int {
	return xxx_messageInfo_RateLimiting_Config.Size(m)
}
func (m *RateLimiting_Config) XXX_DiscardUnknown() {
	xxx_messageInfo_RateLimiting_Config.DiscardUnknown(m)
}

var xxx_messageInfo_RateLimiting_Config proto.InternalMessageInfo

func (m *RateLimiting_Config) GetScope() Scope {
	if m != nil {
		return m.Scope
	}
	return Scope_LOCAL
}

func (m *RateLimiting_Config) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RateLimiting_Config) GetBurst() uint64 {
	if m != nil {
		return m.Burst
	}
	return 0
}

func (m *RateLimiting_Config) GetInterval() *durationpb.Duration {
	if m != nil {
		return m.Interval
	}
	return nil
}

func init() {
	proto.RegisterType((*RateLimiting)(nil), "io.opensergo.policy.v1alpha1.RateLimiting")
	proto.RegisterType((*RateLimiting_Config)(nil), "io.opensergo.policy.v1alpha1.RateLimiting.Config")
}

func init() {
	proto.RegisterFile("policy/v1alpha1/rate_limiting.proto", fileDescriptor_52e97190637d71c6)
}

var fileDescriptor_52e97190637d71c6 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xcf, 0x4a, 0x33, 0x31,
	0x14, 0xc5, 0xe9, 0xd7, 0x76, 0x28, 0xf9, 0xc4, 0x45, 0x70, 0x31, 0x96, 0x22, 0xa5, 0x75, 0xe1,
	0x42, 0xee, 0xd0, 0x8a, 0x0b, 0x77, 0xfe, 0x29, 0x82, 0xe0, 0x2a, 0xdd, 0xb9, 0x91, 0x4c, 0x4c,
	0xc7, 0x60, 0x3a, 0x77, 0xc8, 0xa4, 0x05, 0x5f, 0xc1, 0x07, 0xf1, 0x39, 0x65, 0x6e, 0x66, 0x5a,
	0xed, 0x62, 0x96, 0x27, 0xb9, 0xbf, 0x73, 0xcf, 0xe5, 0xb0, 0x69, 0x81, 0xd6, 0xa8, 0xcf, 0x64,
	0x3b, 0x93, 0xb6, 0x78, 0x97, 0xb3, 0xc4, 0x49, 0xaf, 0x5f, 0xad, 0x59, 0x1b, 0x6f, 0xf2, 0x0c,
	0x0a, 0x87, 0x1e, 0xf9, 0xc8, 0x20, 0x60, 0xa1, 0xf3, 0x52, 0xbb, 0x0c, 0x21, 0x10, 0xd0, 0x10,
	0xc3, 0x58, 0xa1, 0xd3, 0x7b, 0x83, 0x4a, 0x05, 0x6e, 0x38, 0x3a, 0x34, 0x57, 0xb8, 0x5e, 0x63,
	0x5e, 0xff, 0x9e, 0x65, 0x88, 0x99, 0xd5, 0x09, 0xa9, 0x74, 0xb3, 0x4a, 0xde, 0x36, 0x4e, 0x7a,
	0xd3, 0xfc, 0x4f, 0xbe, 0xba, 0xec, 0x48, 0x48, 0xaf, 0x9f, 0xeb, 0x30, 0xfc, 0x96, 0x0d, 0x4a,
	0x6d, 0xb5, 0xf2, 0xe8, 0xe2, 0xce, 0xb8, 0x73, 0xf1, 0x7f, 0x7e, 0x0e, 0x7f, 0x92, 0xd1, 0xea,
	0x66, 0x19, 0x2c, 0xeb, 0x59, 0xb1, 0xa3, 0xf8, 0x13, 0x8b, 0x14, 0xe6, 0x2b, 0x93, 0xc5, 0xff,
	0x88, 0x9f, 0x41, 0xdb, 0x65, 0xf0, 0x7b, 0x3b, 0x3c, 0x10, 0x28, 0x6a, 0x03, 0xbe, 0x60, 0x91,
	0x54, 0x55, 0xda, 0xb8, 0x4b, 0x56, 0x97, 0xed, 0x56, 0x8f, 0xd2, 0xda, 0x54, 0xaa, 0x8f, 0x3b,
	0x62, 0x44, 0xcd, 0x0e, 0xbf, 0x3b, 0x2c, 0x0a, 0xc6, 0xfc, 0x86, 0xf5, 0x4b, 0x85, 0x85, 0xa6,
	0xd3, 0x8e, 0xe7, 0xd3, 0x76, 0xbf, 0x65, 0x35, 0x2a, 0x02, 0xc1, 0x4f, 0x58, 0x9f, 0x1a, 0xa3,
	0xab, 0x7a, 0x22, 0x88, 0xea, 0x35, 0xdd, 0xb8, 0xd2, 0x53, 0xc0, 0x9e, 0x08, 0x82, 0x5f, 0xb3,
	0x81, 0xc9, 0xbd, 0x76, 0x5b, 0x69, 0xe3, 0x1e, 0x25, 0x3f, 0x85, 0x50, 0x04, 0x34, 0x45, 0xc0,
	0xa2, 0x2e, 0x42, 0xec, 0x46, 0xef, 0x27, 0x2f, 0xe3, 0x7d, 0x18, 0x83, 0x89, 0x2c, 0x4c, 0x72,
	0xd0, 0x6e, 0x1a, 0x91, 0xc1, 0xd5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x98, 0xfe, 0x21,
	0x54, 0x02, 0x00, 0x00,
}
