// Code generated by protoc-gen-deepcopy. DO NOT EDIT.

package v1alpha1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using RateLimiting within kubernetes types, where deepcopy-gen is used.
func (in *RateLimiting) DeepCopyInto(out *RateLimiting) {
	p := proto.Clone(in).(*RateLimiting)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimiting. Required by controller-gen.
func (in *RateLimiting) DeepCopy() *RateLimiting {
	if in == nil {
		return nil
	}
	out := new(RateLimiting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new RateLimiting. Required by controller-gen.
func (in *RateLimiting) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
