// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for RateLimit
func (this *RateLimit) MarshalJSON() ([]byte, error) {
	str, err := RateLimitMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RateLimit
func (this *RateLimit) UnmarshalJSON(b []byte) error {
	return RateLimitUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RateLimit_Config
func (this *RateLimit_Config) MarshalJSON() ([]byte, error) {
	str, err := RateLimitMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RateLimit_Config
func (this *RateLimit_Config) UnmarshalJSON(b []byte) error {
	return RateLimitUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	RateLimitMarshaler   = &jsonpb.Marshaler{}
	RateLimitUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
