// Copyright 2023, OpenSergo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "opensergo.io/api/client/pkg/apis/policy/v1alpha1"
)

// FakeConcurrencyLimitings implements ConcurrencyLimitingInterface
type FakeConcurrencyLimitings struct {
	Fake *FakePolicyV1alpha1
	ns   string
}

var concurrencylimitingsResource = v1alpha1.SchemeGroupVersion.WithResource("concurrencylimitings")

var concurrencylimitingsKind = v1alpha1.SchemeGroupVersion.WithKind("ConcurrencyLimiting")

// Get takes name of the concurrencyLimiting, and returns the corresponding concurrencyLimiting object, and an error if there is any.
func (c *FakeConcurrencyLimitings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ConcurrencyLimiting, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(concurrencylimitingsResource, c.ns, name), &v1alpha1.ConcurrencyLimiting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConcurrencyLimiting), err
}

// List takes label and field selectors, and returns the list of ConcurrencyLimitings that match those selectors.
func (c *FakeConcurrencyLimitings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ConcurrencyLimitingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(concurrencylimitingsResource, concurrencylimitingsKind, c.ns, opts), &v1alpha1.ConcurrencyLimitingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ConcurrencyLimitingList{ListMeta: obj.(*v1alpha1.ConcurrencyLimitingList).ListMeta}
	for _, item := range obj.(*v1alpha1.ConcurrencyLimitingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested concurrencyLimitings.
func (c *FakeConcurrencyLimitings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(concurrencylimitingsResource, c.ns, opts))

}

// Create takes the representation of a concurrencyLimiting and creates it.  Returns the server's representation of the concurrencyLimiting, and an error, if there is any.
func (c *FakeConcurrencyLimitings) Create(ctx context.Context, concurrencyLimiting *v1alpha1.ConcurrencyLimiting, opts v1.CreateOptions) (result *v1alpha1.ConcurrencyLimiting, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(concurrencylimitingsResource, c.ns, concurrencyLimiting), &v1alpha1.ConcurrencyLimiting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConcurrencyLimiting), err
}

// Update takes the representation of a concurrencyLimiting and updates it. Returns the server's representation of the concurrencyLimiting, and an error, if there is any.
func (c *FakeConcurrencyLimitings) Update(ctx context.Context, concurrencyLimiting *v1alpha1.ConcurrencyLimiting, opts v1.UpdateOptions) (result *v1alpha1.ConcurrencyLimiting, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(concurrencylimitingsResource, c.ns, concurrencyLimiting), &v1alpha1.ConcurrencyLimiting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConcurrencyLimiting), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeConcurrencyLimitings) UpdateStatus(ctx context.Context, concurrencyLimiting *v1alpha1.ConcurrencyLimiting, opts v1.UpdateOptions) (*v1alpha1.ConcurrencyLimiting, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(concurrencylimitingsResource, "status", c.ns, concurrencyLimiting), &v1alpha1.ConcurrencyLimiting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConcurrencyLimiting), err
}

// Delete takes name of the concurrencyLimiting and deletes it. Returns an error if one occurs.
func (c *FakeConcurrencyLimitings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(concurrencylimitingsResource, c.ns, name, opts), &v1alpha1.ConcurrencyLimiting{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeConcurrencyLimitings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(concurrencylimitingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ConcurrencyLimitingList{})
	return err
}

// Patch applies the patch and returns the patched concurrencyLimiting.
func (c *FakeConcurrencyLimitings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ConcurrencyLimiting, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(concurrencylimitingsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ConcurrencyLimiting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConcurrencyLimiting), err
}
