// Copyright 2023, OpenSergo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "opensergo.io/api/client/pkg/apis/policy/v1alpha1"
)

// FakeConcurrencyLimits implements ConcurrencyLimitInterface
type FakeConcurrencyLimits struct {
	Fake *FakePolicyV1alpha1
	ns   string
}

var concurrencylimitsResource = v1alpha1.SchemeGroupVersion.WithResource("concurrencylimits")

var concurrencylimitsKind = v1alpha1.SchemeGroupVersion.WithKind("ConcurrencyLimit")

// Get takes name of the concurrencyLimit, and returns the corresponding concurrencyLimit object, and an error if there is any.
func (c *FakeConcurrencyLimits) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ConcurrencyLimit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(concurrencylimitsResource, c.ns, name), &v1alpha1.ConcurrencyLimit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConcurrencyLimit), err
}

// List takes label and field selectors, and returns the list of ConcurrencyLimits that match those selectors.
func (c *FakeConcurrencyLimits) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ConcurrencyLimitList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(concurrencylimitsResource, concurrencylimitsKind, c.ns, opts), &v1alpha1.ConcurrencyLimitList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ConcurrencyLimitList{ListMeta: obj.(*v1alpha1.ConcurrencyLimitList).ListMeta}
	for _, item := range obj.(*v1alpha1.ConcurrencyLimitList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested concurrencyLimits.
func (c *FakeConcurrencyLimits) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(concurrencylimitsResource, c.ns, opts))

}

// Create takes the representation of a concurrencyLimit and creates it.  Returns the server's representation of the concurrencyLimit, and an error, if there is any.
func (c *FakeConcurrencyLimits) Create(ctx context.Context, concurrencyLimit *v1alpha1.ConcurrencyLimit, opts v1.CreateOptions) (result *v1alpha1.ConcurrencyLimit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(concurrencylimitsResource, c.ns, concurrencyLimit), &v1alpha1.ConcurrencyLimit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConcurrencyLimit), err
}

// Update takes the representation of a concurrencyLimit and updates it. Returns the server's representation of the concurrencyLimit, and an error, if there is any.
func (c *FakeConcurrencyLimits) Update(ctx context.Context, concurrencyLimit *v1alpha1.ConcurrencyLimit, opts v1.UpdateOptions) (result *v1alpha1.ConcurrencyLimit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(concurrencylimitsResource, c.ns, concurrencyLimit), &v1alpha1.ConcurrencyLimit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConcurrencyLimit), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeConcurrencyLimits) UpdateStatus(ctx context.Context, concurrencyLimit *v1alpha1.ConcurrencyLimit, opts v1.UpdateOptions) (*v1alpha1.ConcurrencyLimit, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(concurrencylimitsResource, "status", c.ns, concurrencyLimit), &v1alpha1.ConcurrencyLimit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConcurrencyLimit), err
}

// Delete takes name of the concurrencyLimit and deletes it. Returns an error if one occurs.
func (c *FakeConcurrencyLimits) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(concurrencylimitsResource, c.ns, name, opts), &v1alpha1.ConcurrencyLimit{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeConcurrencyLimits) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(concurrencylimitsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ConcurrencyLimitList{})
	return err
}

// Patch applies the patch and returns the patched concurrencyLimit.
func (c *FakeConcurrencyLimits) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ConcurrencyLimit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(concurrencylimitsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ConcurrencyLimit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConcurrencyLimit), err
}
