// Copyright 2023, OpenSergo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "opensergo.io/api/client/pkg/apis/policy/v1alpha1"
)

// FakeRateLimitings implements RateLimitingInterface
type FakeRateLimitings struct {
	Fake *FakePolicyV1alpha1
	ns   string
}

var ratelimitingsResource = v1alpha1.SchemeGroupVersion.WithResource("ratelimitings")

var ratelimitingsKind = v1alpha1.SchemeGroupVersion.WithKind("RateLimiting")

// Get takes name of the rateLimiting, and returns the corresponding rateLimiting object, and an error if there is any.
func (c *FakeRateLimitings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RateLimiting, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ratelimitingsResource, c.ns, name), &v1alpha1.RateLimiting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RateLimiting), err
}

// List takes label and field selectors, and returns the list of RateLimitings that match those selectors.
func (c *FakeRateLimitings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RateLimitingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ratelimitingsResource, ratelimitingsKind, c.ns, opts), &v1alpha1.RateLimitingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RateLimitingList{ListMeta: obj.(*v1alpha1.RateLimitingList).ListMeta}
	for _, item := range obj.(*v1alpha1.RateLimitingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested rateLimitings.
func (c *FakeRateLimitings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ratelimitingsResource, c.ns, opts))

}

// Create takes the representation of a rateLimiting and creates it.  Returns the server's representation of the rateLimiting, and an error, if there is any.
func (c *FakeRateLimitings) Create(ctx context.Context, rateLimiting *v1alpha1.RateLimiting, opts v1.CreateOptions) (result *v1alpha1.RateLimiting, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ratelimitingsResource, c.ns, rateLimiting), &v1alpha1.RateLimiting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RateLimiting), err
}

// Update takes the representation of a rateLimiting and updates it. Returns the server's representation of the rateLimiting, and an error, if there is any.
func (c *FakeRateLimitings) Update(ctx context.Context, rateLimiting *v1alpha1.RateLimiting, opts v1.UpdateOptions) (result *v1alpha1.RateLimiting, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ratelimitingsResource, c.ns, rateLimiting), &v1alpha1.RateLimiting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RateLimiting), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRateLimitings) UpdateStatus(ctx context.Context, rateLimiting *v1alpha1.RateLimiting, opts v1.UpdateOptions) (*v1alpha1.RateLimiting, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ratelimitingsResource, "status", c.ns, rateLimiting), &v1alpha1.RateLimiting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RateLimiting), err
}

// Delete takes name of the rateLimiting and deletes it. Returns an error if one occurs.
func (c *FakeRateLimitings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(ratelimitingsResource, c.ns, name, opts), &v1alpha1.RateLimiting{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRateLimitings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ratelimitingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RateLimitingList{})
	return err
}

// Patch applies the patch and returns the patched rateLimiting.
func (c *FakeRateLimitings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RateLimiting, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ratelimitingsResource, c.ns, name, pt, data, subresources...), &v1alpha1.RateLimiting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RateLimiting), err
}
